spring:
  application:
    name: your-application-name
  main:
    banner-mode: "off" # 배너 출력 끄기 (선택 사항)
  logging:
    level:
      com.sundayCinema.sundayCinema.movie.api.TMDB: DEBUG
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 9397wkdwjd
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-ID}
            clientSecret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-SECRET}
  youtubeApiKey: ${YOUTUBE_API_KEY}
  KdmbApiKey: ${KDMB_API_KEY}
  KobisApiKEY: ${KOBIS_API_KEY}
#  tmdbKey : ${TMDB_API_KEY}
jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 429